export namespace ErrorCodes {
    export const AUTH_FORBIDDEN = 'AUTH_FORBIDDEN'
    export const AUTH_ACCOUNT_NOT_FOUND = 'AUTH_ACCOUNT_NOT_FOUND'
    export const AUTH_ACCOUNT_PENDING_ACTIVATION = 'AUTH_ACCOUNT_PENDING_ACTIVATION'
    export const AUTH_ACCOUNT_EXISTS = 'AUTH_ACCOUNT_EXISTS'
    export const AUTH_REQUEST_EXPIRED = 'AUTH_REQUEST_EXPIRED'
    export const AUTH_REQUEST_NOT_FOUND = 'AUTH_REQUEST_NOT_FOUND'
}