services:
  prometheus:
    image: prom/prometheus
    ports:
      - '8002:9090'
    volumes:
      - 
        type: bind
        source: config
        target: /etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web.yml'
volumes:
  config: 
    name: prometheus-config
