import { registerEnumType } from "@nestjs/graphql";

export enum ErrorCodes {
    UPLOAD_MEDIA_NOT_FOUND = 'UPLOAD_MEDIA_NOT_FOUND',
    UPLOAD_FILE_NOT_FOUND = 'UPLOAD_FILE_NOT_FOUND',

    AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
    AUTH_ACCOUNT_NOT_FOUND = 'AUTH_ACCOUNT_NOT_FOUND',
    AUTH_ACCOUNT_PENDING_ACTIVATION = 'AUTH_ACCOUNT_PENDING_ACTIVATION',
    AUTH_ACCOUNT_EXISTS = 'AUTH_ACCOUNT_EXISTS',
    AUTH_REQUEST_EXPIRED = 'AUTH_REQUEST_EXPIRED',
    AUTH_REQUEST_NOT_FOUND = 'AUTH_REQUEST_NOT_FOUND',

    ORG_BRANCH_NOT_FOUND = 'ORG_BRANCH_NOT_FOUND',

    PRODUCT_IMPORT_EMPTY_RECORDS = 'PRODUCT_IMPORT_EMPTY_RECORDS',
    PRODUCT_PRICE_IMPORT_EMPTY_RECORDS = 'PRODUCT_PRICE_IMPORT_EMPTY_RECORDS',

    SALE_BRANCH_SALE_CHANNEL_NOT_FOUND = 'SALE_BRANCH_SALE_CHANNEL_NOT_FOUND',
    SALE_ORDER_IMPORT_PARSE_FAILURE = 'SALE_ORDER_IMPORT_PARSE_FAILURE',
}

registerEnumType(ErrorCodes, {
  name: 'ErrorCodes',
});