export namespace ErrorCodes {
    export const UPLOAD_MEDIA_NOT_FOUND = 'UPLOAD_MEDIA_NOT_FOUND'
    export const UPLOAD_FILE_NOT_FOUND = 'UPLOAD_FILE_NOT_FOUND'

    export const AUTH_FORBIDDEN = 'AUTH_FORBIDDEN'
    export const AUTH_ACCOUNT_NOT_FOUND = 'AUTH_ACCOUNT_NOT_FOUND'
    export const AUTH_ACCOUNT_PENDING_ACTIVATION = 'AUTH_ACCOUNT_PENDING_ACTIVATION'
    export const AUTH_ACCOUNT_EXISTS = 'AUTH_ACCOUNT_EXISTS'
    export const AUTH_REQUEST_EXPIRED = 'AUTH_REQUEST_EXPIRED'
    export const AUTH_REQUEST_NOT_FOUND = 'AUTH_REQUEST_NOT_FOUND'

    export const ORG_BRANCH_NOT_FOUND = 'ORG_BRANCH_NOT_FOUND'

    export const PRODUCT_IMPORT_EMPTY_RECORDS = 'PRODUCT_IMPORT_EMPTY_RECORDS'
    export const PRODUCT_PRICE_IMPORT_EMPTY_RECORDS = 'PRODUCT_PRICE_IMPORT_EMPTY_RECORDS'

    export const SALE_BRANCH_SALE_CHANNEL_NOT_FOUND = 'SALE_BRANCH_SALE_CHANNEL_NOT_FOUND'
    export const SALE_ORDER_IMPORT_PARSE_FAILURE = 'SALE_ORDER_IMPORT_PARSE_FAILURE'

}